language: python
python:
  - '3.8'
env:
  - DJANGO_DEVELOPMENT=True
install:
  - pipenv sync
script:
  - pipenv run python manage.py check
  - pipenv run python manage.py test
  - pipenv run python manage.py makemigrations --dry-run --check
