dist: focal
language: python
python:
  - '3.9'
env:
  - DJANGO_DEVELOPMENT=True
install:
  - pip install --upgrade pipenv
  - pipenv sync
script:
  - pipenv run python manage.py check
  - pipenv run python manage.py test
  - pipenv run python manage.py makemigrations --dry-run --check
